### ISSUE TITLE
Restrição de inclusão de usuários em áreas de trabalho

### ISSUE THREAD

**Issue by LeandroJatai** [interlegis/saap#4]
Atualmente o sistema não restringe o cadastro de um operador em mais de uma área de trabalho (AT), mas não sabe lidar com o caso de um usuário estar em mais de uma AT.

Existem duas alternativas a implementar:
1. Não permitir que um usuário seja incluso em mais de uma AT. Isso é mais fácil de fazer e se resume a uma validação na inclusão/edição de operadores
2. Caso o usuário esteja em mais de uma AT, ao logar deverá ser dado a ele a possibilidade de em que AT sua sessão será iniciada... tal solução envolve uma mudança no crud_custom na app globalroles e é bem mais complexa que a alternativa 1.

**Comment by sesostris** [comment]
É extremamente incomum que uma pessoa atue em mais de um gabinete parlamentar ao mesmo tempo, não fazendo sentido que um usuário atue em mais de uma AT. Creio que a melhor alternativa é impedir que um usuário seja lotado em mais de uma área.
Na eventualidade de uma pessoa precisar atuar em mais de uma AT, pode-se criar vários usuários para ele, cada um lotado em sua respectiva AT.

**Comment by ojonathacardoso** [comment]
Concordo com o @sesostris... Porém, pode ser que, eventualmente, haja alguma Câmara pequena que não tenha um assessor por parlamentar, mas seja um para todos, ou alguns para todos...
Acho que, no momento, caso haja essa necessidade, cria-se um usuário por AT/vereador... Mais ou menos como é no SAPL. 

Se no futuro houver algo que exija a possibilidade de "alternância" de AT, aí podemos discutir alguma forma mais "tecnológica" de resolver isto.

**Comment by LeandroJatai** [comment]
@ojonathacardoso seria importante de imediato haver apenas um filtro no registro de operadores de AT, excluindo usuários do selectbox que estejam em outra AT.

**Comment by ojonathacardoso** [comment]
@LeandroJatai Creio que isso é simples, algo do tipo definir um conjunto de Fields do banco como unique, tipo operador + AT.

**Comment by ojonathacardoso** [comment]
Constatei que ao ter mais de uma área de trabalho associada a um usuário/operador, os dados, por exemplo, de contato que aparecem são apenas os da primeira AT. 
Por isso, é importante haver um seletor de área de trabalho.
Acho importante haver a possibilidade desse vínculo, pois analisando bem, não haveria sentido em se ter uma tabela M x N denominada operadores, mas apenas um campo no usuário vinculando-o a respectiva Área de Trabalho.
Existem câmaras que um único servidor faz todo o gerenciamento. 

Sendo assim, vou estudar essa questão para em breve possibilitar a troca da área de trabalho utilizada.

**Comment by ojonathacardoso** [comment]
A versão 3.1.3 do SAAP conta com sistema completo de áreas de trabalho, onde se um usuário possui vínculo a mais de uma área (vários operadores), ele pode alternar entre a área de trabalho desejada.
