### ISSUE TITLE
Simplificar ambiente de desenvolvimento

### ISSUE THREAD

**Issue by ramiroluz** [interlegis/saap#6]
O ambiente de desenvolvimento não precisa de servidor Web nem servidor de banco de dados.

Ainda, o comando manage.py não funciona pois falta uma configuração para o decouple, seria necessário avaliar se a configuração não poderia ter um valor default caso o arquivo .env não exista.

decouple.UndefinedValueError: INITIAL_VALUE_FORMS_UF option not found and default value was not defined.

**Comment by LeandroRoberto** [comment]
São três variáveis initial_value.......  Elas colocam valores padrão no cadastro de endereço de contatos

**Comment by ramiroluz** [comment]
Sim, posso colocar um valor padrão caso o arquivo .env não exista?

Tipo:
INITIAL_VALUE_FORMS_UF='DF'
INITIAL_VALUE_FORMS_MUNICIPIO='Brasilía'
INITIAL_VALUE_FORMS_CEP='71608-000'
No settings.py:
INITIAL_VALUE_FORMS_UF = config('INITIAL_VALUE_FORMS_UF', default='DF')
INITIAL_VALUE_FORMS_MUNICIPIO = config('INITIAL_VALUE_FORMS_MUNICIPIO', default='Brasília')
INITIAL_VALUE_FORMS_CEP = config('INITIAL_VALUE_FORMS_CEP', default='71608-000')

**Comment by LeandroRoberto** [comment]
Isso...  Default no settings pra Brasília fica legal
