### ISSUE TITLE
Criar instruções de deploy

### ISSUE THREAD

**Issue by ramiroluz** [interlegis/saap#8]
Criar instruções separadas para deploy.
- Em servidor próprio.
- Em hospedagens externas tradicionais, DigitalOcean, Heroku, Locaweb Jelastic, Configr, etc ...

**Comment by ojonathacardoso** [comment]
Para servidor próprio, as instruções já estão criadas em https://github.com/ojonathacardoso/saap/blob/master/docs/deploy.rst

Faltaria, no caso, para hospedagem externa. Podemos esperar surgir a demanda, ou já fazer o teste para escrever o guia.

**Comment by ojonathacardoso** [comment]
@ramiroluz , tendo em vista que agora o SAAP também possui imagem Docker, e como diversas hospedagens permitem o uso dessa tecnologia, será que tais instruções fazem-se necessárias?
